sudo: false
language: java
install: true
jdk:
  - oraclejdk9
#script:
#  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
  - "$HOME/.cache"
#  - '$HOME/.m2/repository'
#  - '$HOME/.sonar/cache'
#deploy:
#  provider: script
#  script: "cp .travis.settings.xml $HOME/.m2/settings.xml && mvn deploy"
#  skip_cleanup: true
#  on:
#    tags: true

after_success:
  - mvn jacoco:report coveralls:jacoco